<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>ThaiWrap.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ThaiWrap/ThaiWrap.csproj" />
    <ProjectReference Include="../ThaiWrap.Formats/ThaiWrap.Formats.csproj" />
  </ItemGroup>

</Project>
